import { FLOW } from '../Facetec';

/**
 * @param id идентификатор операции operation_id
 * @param session идентификатор сесии FaceTec: sessionToken
 * @param partner зашифрованный идентификатор партнера partner_key
 */
export type TConfigGetProps = Record<'id' | 'session' | 'partner', string>;

export type TPaths = Record<
  | 'staticRoot'
  | 'getConfig'
  | 'enrollmentUpload'
  | 'idScanUpload'
  | 'statusUpload',
  string
> & {
  auditTrailPath?: string;
};

type TReceivedPaths = { base_url: string };

export type TConfigPaths = TPaths & TReceivedPaths;

export type TLocaleConfig = Record<string, unknown>;

export type TThemeConfig = Record<
  'overlayCustomization',
  Record<'brandingImage', string>
>;

export type TDowntimeConfig = Record<'value', number>;

export type TConfigProps = Record<
  'ProductionKey' | 'DeviceKeyIdentifier' | 'PublicFaceScanEncryptionKey',
  string
> &
  TConfigGetProps &
  Record<'flow', FLOW> &
  Record<'paths', TConfigPaths> &
  Partial<
    Record<'locale', TLocaleConfig> &
      Record<'theme', TThemeConfig> &
      Record<'downtime', TDowntimeConfig>
  >;

export type TOperationData = Record<
  'description' | 'operation_id' | 'operation_url',
  string
> & {
  result: number;
};

export type TInitializeFromAutogeneratedConfigCallback = (
  initializedSuccessfully: boolean
) => void;

export type TGetConfigProps = Record<
  'production_key' | 'ssh_public_key' | 'device_key' | 'session_path',
  string
> &
  TReceivedPaths & {
    session_timeout: number;
  };
